### ISSUE TITLE
Mover configurações da Vindi para Menu próprio

### ISSUE THREAD

**Issue by laerte-guimaraes** [vindi/vindi-magento2#12]
As configurações do módulo estão inseridas dentro dos Métodos de Pagamento!

Os métodos devem exibir apenas configurações de métodos na Vindi.
Ex: 
- ajuste de parcelas
- transação de verificação
- habilitar/desabiltar

O menu próprio deve disponibilizar as configurações do módulo Vindi.
Ex: 
- habilitar/desabilitar
- chave API
- sandbox/production
- url webhook

**Comment by leonardola** [comment]
Agora as configurações básicas estão em Vindi > Configuração
![captura de tela 2018-08-08 as 9 37 08 am](https://user-images.githubusercontent.com/6342964/43837748-ddf9a72a-9aef-11e8-9f13-69509bcdc131.png)

**Comment by leonardola** [comment]
O habilitar desabilitar deve ficar dentro de Lojas > Configuração > Vendas > Método de pagamento. Pois o magento obriga fazer assim.

**Comment by laerte-guimaraes** [comment]
@leonardola pode alterar o campo Chave do Webhook para somente leitura?

**Comment by leonardola** [comment]
já está como somente leitura
