### ISSUE TITLE
Remover responsabilidades desnecessárias da Classe API

### ISSUE THREAD

**Issue by laerte-guimaraes** [vindi/vindi-magento2#14]
A classe [API](https://github.com/vindi/vindi-magento2/blob/master/app/code/Vindi/Payment/Model/Payment/Api.php) não deve possuir nenhuma responsabilidade além de realizar requisições!

Os métodos relacionados a entidades específicas devem ser movidos (ex: createCustomer/Bill...)

**Comment by leonardola** [comment]
removido funções que não deveriam estar ali com 485f552
