### ISSUE TITLE
Verificar chave API na habilitação dos métodos de pagamento

### ISSUE THREAD

**Issue by laerte-guimaraes** [vindi/vindi-magento2#15]
É possível realizar a verificação da Chave API ao tentar habilitar um método de pagamento da Vindi?

O objetivo, é não deixar o cliente habilitar os métodos (salvar), caso a chave API não esteja setada.
Desse modo, não é necessário validar **$this->apiKey** no _request_ da API, pois caso não possua chave API, não irá chegar no _request_.

**Comment by leonardola** [comment]
corrigido no pull request #13  no arquivo app/code/Vindi/Payment/Model/Config/Backend/ApiKeyValidator.php

**Comment by laerte-guimaraes** [comment]
@leonardola é possível separar em um novo PR?
Acredito que para deixar a validação mais precisa, você pode utilizar o endpoint 
**GET** _/v1/merchants/current_ e verificar se o status é diferente de **inactive**

**Comment by leonardola** [comment]
criado pull request #21 com estas mudanças
