### ISSUE TITLE
Enviar o valor do frete nas faturas

### ISSUE THREAD

**Issue by laerte-guimaraes** [vindi/vindi-magento2#16]
O valor do frete não está sendo enviado, gerando uma inconsistência entre Magento > Vindi.

**Comment by laerte-guimaraes** [comment]
Nesse caso o valor cobrado foi de R$ 45,00; (valor dos produtos, porém sem o frete)

**Comment by leonardola** [comment]
corrigido

**Comment by laerte-guimaraes** [comment]
Validado !
