### ISSUE TITLE
Disponibilizar apenas os status padrões do Magento para atribuição após a conclusão do pedido.

### ISSUE THREAD

**Issue by rtakauti** [vindi/vindi-magento2#18]
![image](https://user-images.githubusercontent.com/5501740/43927340-8ea49c24-9c03-11e8-9b94-69b376940e2b.png)

**Comment by rtakauti** [comment]
![image](https://user-images.githubusercontent.com/5501740/43927340-8ea49c24-9c03-11e8-9b94-69b376940e2b.png)

**Comment by laerte-guimaraes** [comment]
@leonardola pode remover a ClearSale do ambiente Homolog, para verificarmos o comportamento?

**Comment by leonardola** [comment]
@laerte-guimaraes @rtakauti a clearsale não está ativa no site de homologação

**Comment by leonardola** [comment]
Vocês podem me explicar melhor o que está ocorrendo exatamente?

**Comment by laerte-guimaraes** [comment]
@leonardola conforme conversado; No Magento deve ser realizada uma captura offline, e a mesma receber o status configurado nessa opção.

Caso o pagamento seja realizado, vocês devem atualizar a **order** e a **invoice** para o status selecionado.
