### ISSUE TITLE
Na tela de checkout em informações do cartão mudar o label do combobox para "Bandeira" e "Escolha a bandeira..."

### ISSUE THREAD

**Issue by rtakauti** [vindi/vindi-magento2#19]
![image 1](https://user-images.githubusercontent.com/5501740/43927432-ede4562a-9c03-11e8-9a39-4c7a9f538736.png)

**Comment by rtakauti** [comment]
![image 1](https://user-images.githubusercontent.com/5501740/43927432-ede4562a-9c03-11e8-9a39-4c7a9f538736.png)

**Comment by leonardola** [comment]
já havia sido modificada antes com 6ccd323a75e2ccfaed08485299b3546659e1b802
