### ISSUE TITLE
Não é possível realizar uma compra no ambiente de homologação

### ISSUE THREAD

**Issue by rtakauti** [vindi/vindi-magento2#26]
@leonardola  não é possível realizar uma compra no ambiente de homologação erro 400 Bad request, sem o ambiente de homologação não poderemos aprovar as PRs

![image](https://user-images.githubusercontent.com/5501740/44037862-c6ae9b02-9eeb-11e8-83a2-dc6e8297c3d3.png)

**Comment by laerte-guimaraes** [comment]
O cartão está incorreto.
