### ISSUE TITLE
Erro ao enviar email

### ISSUE THREAD

**Issue by hectorcanaimero** [vindi/vindi-magento2#46]
**Descreva o bug**
O Magento 2.3 está reconhecendo como um caminho errado ao enviar o email, isso também acontece ao fazer a compra pela loja. O processo com o Vindi funciona perfeitamente, só existe o detalhe de enviar o email com a informação esperada

**Como reproduzir**
Passos para reprodução do comportamento:
1. Vá para 'Vendas->Pedidos->View Pedido'
2. Click em 'Enviar e-mail'
3. Veja erro
Invalid template file: 'Vindi_Payment::info/cc.phtml' in module: 'Vindi_Payment' block's name: 'info\cc_0'

**Comportamento Esperado**
Ao clicar, o sistema deve enviar o email com as informações esperadas para esse modelo.

**Prints de tela**
![captura de tela em 2019-02-25 09-21-51](https://user-images.githubusercontent.com/158916/53340241-ec4ee780-38de-11e9-8348-ff59903ce314.png)

**Desktop (favor completar as seguintes  informações):**
 - OS: Linux Mint, Windows, OS
 - Browser Firefox, Google Chrome
 - Magento 2.3
 - PHP 7.1

**Comment by rtakauti** [comment]
Bom dia @hectorcanaimero, 
Obrigado pelo feedback, já iremos colocar para analise.

**Comment by hectorcanaimero** [comment]
Consegui resolver o problema copiando a pasta do **adminhtml/templates/info/cc.html** para o **frontend/templates/info/cc.html**
