### ISSUE TITLE
Realizar ajuste na seleção das bandeiras de cartão de crédito

### ISSUE THREAD

**Issue by rtakauti** [vindi/vindi-magento2#8]
Realizar ajuste na lista "hard coded" das bandeiras de cartão de crédito

**Comment by leonardola** [comment]
Como já conversado por call. Esta lista hardcoded precisará continuar existindo. Pois ela é necessária para "traduzir" os nomes das bandeiras que o magento usa para o que a api utiliza. O que fiz foi adicionar um validador no #6 para verificar se a bandeira está ou não disponível para ser usada.

**Comment by rtakauti** [comment]
@leonardola acabei de fazer o teste com varias bandeiras, e se for discover,elo ou alelo como podemos colocar no frontend a opção para selecionar a bandeira? combobox?

**Comment by laerte-guimaraes** [comment]
@leonardola não está sendo possível realizar compras com as bandeiras Elo e Discovery;

Para resolver esse ponto, poderia ser inserido uma lista com as bandeiras disponíveis para o cliente selecionar?

**Comment by leonardola** [comment]
removido listagem hardcoded. Modificações estão no pull request #13
