### ISSUE TITLE
Pix Payments on Magento Plugin

### ISSUE THREAD

**Issue by diegolearnstocode** [vindi/vindi-magento2#84]
Vindi & Yapay offer Pix Payments, however this method is not currently available on the magento plugin and we would really like to have it available

**Comment by tkusuki** [comment]
> Vindi & Yapay offer Pix Payments, however this method is not currently available on the magento plugin and we would really like to have it available

Pix payments was implemented on release [1.4.0 ](https://github.com/vindi/vindi-magento2/releases/tag/1.4.0)
