### ISSUE TITLE
Ajustar requestId para que tenhamos uma ordem crescente sem sobrescrita

### ISSUE THREAD

**Issue by rtakauti** [vindi/vindi-magento2#9]
Referente ao PR #3

**Comment by leonardola** [comment]
Ajustado com 3d1d707704e4b7fffbbf8458ba363414536753e8

**Comment by laerte-guimaraes** [comment]
Resolvido no [commit](https://github.com/vindi/vindi-magento2/pull/3/commits/635e6d5afafaf5c5a58f095201daf2074fa2cc2c)
